#!/usr/bin/env python3
"""
Parse the linker .map file produced by the ROM build and extract RAM addresses
for all key battle globals. Outputs addresses.py for use by the env.

Usage:
    python scripts/extract_addresses.py roms/pokeemerald-rogue.map
"""

import re
import sys
from pathlib import Path

# Symbols we need for battle observations and control
TARGET_SYMBOLS = [
    # Battle state
    "gBattleMons",
    "gBattleOutcome",
    "gBattleTypeFlags",
    "gBattleWeather",
    "gBattlersCount",
    "gBattlerPositions",
    "gBattlerPartyIndexes",
    # Move / action state
    "gCurrentMove",
    "gChosenMove",
    "gChosenActionByBattler",
    "gBattleMoveDamage",
    "gMoveResultFlags",
    # Side / status
    "gSideStatuses",
    "gSideTimers",
    "gDisableStructs",
    "gProtectStructs",
    "gStatuses3",
    "gWishFutureKnock",
    # Party data
    "gPlayerParty",
    "gEnemyParty",
    "gPlayerPartyCount",
    "gEnemyPartyCount",
    # ROM tables (these will be in ROM space 0x08xxxxxx, not RAM)
    "gBattleMoves",
    "gBaseStats",
    # Input / battle control
    "gBattleControllerExecFlags",
    "gBattleMainFunc",
    # Rogue assistant header (pointer chain root)
    "rogueAssistantHeader",
    "gSaveBlock1Ptr",
    "gSaveBlock2Ptr",
]

# .map line format varies by linker, common patterns:
#   0x0200xxxx   gBattleMons
#   .data.gBattleMons   0x0200xxxx   0x58
MAP_PATTERNS = [
    # GNU ld: "                0x0200xxxx                gBattleMons"
    re.compile(r"^\s+(0x[0-9a-fA-F]{8})\s+(\w+)\s*$"),
    # Section line: ".bss.gBattleMons  0x0200xxxx  0x58"
    re.compile(r"^\s*\.\S*\.(\w+)\s+(0x[0-9a-fA-F]{8})\s+"),
]


def parse_map(map_path: Path) -> dict[str, int]:
    found = {}
    target_set = set(TARGET_SYMBOLS)

    with open(map_path, "r", errors="replace") as f:
        for line in f:
            for pat in MAP_PATTERNS:
                m = pat.match(line)
                if m:
                    if pat.groups == 2 and m.lastindex == 2:
                        addr_str, sym = m.group(1), m.group(2)
                    else:
                        sym, addr_str = m.group(1), m.group(2)
                    if sym in target_set:
                        found[sym] = int(addr_str, 16)
                    break

    return found


def write_addresses(found: dict[str, int], out_path: Path):
    missing = [s for s in TARGET_SYMBOLS if s not in found]

    lines = [
        "# AUTO-GENERATED by scripts/extract_addresses.py — do not edit by hand",
        "# Re-run after rebuilding the ROM.",
        "",
        "# GBA memory regions for reference:",
        "# EWRAM (work RAM): 0x02000000 – 0x0203FFFF  (256 KB)",
        "# ROM:              0x08000000 – 0x09FFFFFF",
        "",
        "ADDRESSES: dict[str, int] = {",
    ]
    for sym in TARGET_SYMBOLS:
        addr = found.get(sym)
        if addr is not None:
            lines.append(f'    "{sym}": {hex(addr)},')
        else:
            lines.append(f'    # "{sym}": NOT FOUND IN MAP',)
    lines += ["}", ""]

    if missing:
        lines += [
            f"# WARNING: {len(missing)} symbol(s) not found in map file:",
        ]
        for s in missing:
            lines.append(f"#   {s}")
        lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path}  ({len(found)}/{len(TARGET_SYMBOLS)} symbols found)")
    if missing:
        print(f"Missing: {missing}")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <path/to/pokeemerald-rogue.map>")
        sys.exit(1)

    map_path = Path(sys.argv[1])
    if not map_path.exists():
        print(f"ERROR: {map_path} not found")
        sys.exit(1)

    found = parse_map(map_path)
    out_path = Path("memory/addresses.py")
    out_path.parent.mkdir(exist_ok=True)
    write_addresses(found, out_path)


if __name__ == "__main__":
    main()
