# AUTO-GENERATED by scripts/extract_addresses.py — do not edit by hand
# Re-run after rebuilding the ROM:
#   python scripts/extract_addresses.py roms/pokeemerald-rogue.map
#
# Placeholder values — all 0x0 until the ROM is built and the map file is parsed.

# GBA memory regions:
# EWRAM (work RAM): 0x02000000 – 0x0203FFFF  (256 KB)
# ROM:              0x08000000 – 0x09FFFFFF

ADDRESSES: dict[str, int] = {
    # Battle state
    "gBattleMons":              0x0,  # BattlePokemon[4], ~0x58 bytes each
    "gBattleOutcome":           0x0,  # u8
    "gBattleTypeFlags":         0x0,  # u32
    "gBattleWeather":           0x0,  # u16
    "gBattlersCount":           0x0,  # u8
    "gBattlerPositions":        0x0,  # u8[4]
    "gBattlerPartyIndexes":     0x0,  # u16[4]
    # Move / action state
    "gCurrentMove":             0x0,  # u16
    "gChosenMove":              0x0,  # u16
    "gChosenActionByBattler":   0x0,  # u8[4]
    "gBattleMoveDamage":        0x0,  # s32
    "gMoveResultFlags":         0x0,  # u8
    # Side / status
    "gSideStatuses":            0x0,  # u16[2]
    "gSideTimers":              0x0,  # SideTimer[2]
    "gDisableStructs":          0x0,  # DisableStruct[4]
    "gProtectStructs":          0x0,  # ProtectStruct[4]
    "gStatuses3":               0x0,  # u32[4]
    "gWishFutureKnock":         0x0,  # WishFutureKnock
    # Party data
    "gPlayerParty":             0x0,  # Pokemon[6], 104 bytes each
    "gEnemyParty":              0x0,  # Pokemon[6]
    "gPlayerPartyCount":        0x0,  # u8
    "gEnemyPartyCount":         0x0,  # u8
    # ROM tables
    "gBattleMoves":             0x0,  # BattleMove[] in ROM
    "gBaseStats":               0x0,  # BaseStats[] in ROM
    # Misc
    "gBattleControllerExecFlags": 0x0,
    "gBattleMainFunc":          0x0,
    # Rogue save block pointers
    "rogueAssistantHeader":     0x0,
    "gSaveBlock1Ptr":           0x0,
    "gSaveBlock2Ptr":           0x0,
}
